services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: contractmirror_php
        working_dir: /var/www/html
        env_file:
            -   .env.prod
        environment:
            APP_ENV: prod
            APP_SECRET: ${APP_SECRET}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4.1-mini}
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8
            CRYPTO_WALLET_ADDRESS: ${CRYPTO_WALLET_ADDRESS}
            USDT_TRON_CONTRACT_ADDRESS: ${USDT_TRON_CONTRACT_ADDRESS}
        volumes:
            - ./:/var/www/html
            - ./var:/var/www/html/var
        depends_on:
            database:
                condition: service_healthy

    nginx:
        image: nginx:1.27-alpine
        container_name: contractmirror_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    database:
        image: postgres:16-alpine
        container_name: contractmirror_database
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/postgresql/data:rw
    redis:
        image: redis:7-alpine
        command: >
            redis-server
            --appendonly yes
            --protected-mode yes
            --bind 0.0.0.0
            --requirepass ${REDIS_PASSWORD}
        expose:
            - "6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped

volumes:
    database_data:
    redis_data:
